# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    cocoapods
  end

  desc "Sync certificates"
  lane :sync_certificates do
    create_keychain(
      name:ENV['MATCH_KEYCHAIN_NAME'],
      password:ENV['MATCH_KEYCHAIN_PASSWORD'],
      default_keychain:true,
      unlock:true,
      timeout:3600,
      add_to_search_list:true
      )

     match(
      type: "adhoc",
      readonly: true,
      keychain_name:ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password:ENV['MATCH_KEYCHAIN_PASSWORD']
      )
    end

  desc "Push a new beta build to TestFlight"
  lane :beta do

    sync_certificates

    asc_key_content = ENV['APP_STORE_CONNECT_API_KEY_CONTENT']
    asc_issuer_id = ENV['APP_STORE_CONNECT_ISSUER_ID']
    asc_key_id = ENV['APP_STORE_CONNECT_API_KEY_ID']

    #发布
    app_store_connect_api_key(
      key_id: asc_key_id,
      issuer_id: asc_issuer_id,
      key_content: asc_key_content,
      is_key_content_base64: true
    )

    increment_build_number(xcodeproj: "AFJ-Visual-Swift.xcodeproj")
    build_app(
      scheme: "AFJ-Visual-Swift",
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        method: "adhoc",
        provisioningProfiles: {
          "com.alfred.AFJ-Visual-Swift" => "match AdHoc com.alfred.AFJ-Visual-Swift",
        }
      },
      )
    upload_to_testflight
  end
end
