name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '14.3.1'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: Install gems
        run: bundle install
      - name: Install pods
        run: bundle exec pod install
      - name: Build and upload
        run: bundle exec fastlane beta
        env:
          MATCH_KEYCHAIN_NAME: ${{Secrets.MATCH_KEYCHAIN_NAME}}
          MATCH_KEYCHAIN_PASSWORD: ${{Secrets.MATCH_KEYCHAIN_PASSWORD}}
          MATCH_PASSWORD: ${{Secrets.MATCH_PASSWORD}}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{Secrets.MATCH_GIT_BASIC_AUTHORIZATION}}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{Secrets.APP_STORE_CONNECT_API_KEY_CONTENT}}
          APP_STORE_CONNECT_ISSUER_ID: ${{Secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID}}
          APP_STORE_CONNECT_API_KEY_ID: ${{Secrets.APP_STORE_CONNECT_API_KEY_KEY_ID}}
